RS-2847: Remove unnecessary println
franklin-ai/image-tiff pull request #4
Opened 2024-04-07 22:44 UTC by shan-pandian

This println is spamming stdout when running test-data-generator to produce the test images.

2024-04-07 23:43 UTC, jayvdb requested changes
Please remove all of the printlns

2024-04-08 00:54 UTC, shan-pandian commented
> Please remove all of the printlns

they are not getting printed as part of our image generation code flow

2024-04-08 01:05 UTC, jayvdb commented
we discussed this on Friday and consensus was that you would remove all of them.
https://github.com/search?q=repo%3Aimage-rs%2Fimage-tiff%20println&type=code contains none - so they were added by the customisations that we have made, and they all need to be removed, otherwise this issue will resurface unexpectedly when we use more of this lib.

2024-04-08 02:26 UTC, jayvdb approved these changes

2024-04-08 02:45 UTC, merged